version: 1
runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

handlers:
- url /(.*\.(html|css|js|png|gif))
  static_files: static/\1
  upload: static/(.*\.(html|css|js|png|gif))

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: server.js

