version: 1
runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

handlers:
- url /client/(.*\.(html|css|js|png|gif|jpg|jpeg))
  static_files: client/\1
  upload: client/(.*\.(html|css|js|png|gif|jpg|jpeg))

- url: /
  static_files: client/index.html
  upload: client/index.html

- url: /.*
  script: server.js

